# NoNameCore by Aelithron
# A core plugin to add extras to the Not-yet-named Server.

# Prefix - Starts every message sent by the plugin.
# Color codes supported here, guide: https://wiki.ess3.net/mc
Prefix: "&8[&dNo Name Core&8]"

# Welcome Message - Sends to players after they join (3 sec delay)
# Disable by setting the first line of the message to "DISABLED"
# Color codes supported here, guide: https://wiki.ess3.net/mc
# Placeholder %allplayers% for all online players
WelcomeMessage:
  - "&8-- &dNot-yet-named Server &8--"
  - "&9Join the Discord: /discord"
  - "&aPlayers online: &f%allplayers%"

# Server Rules
# Used in the /rules command.
# Don't place bullet points or number rules, they are numbered automatically.
# A header is also pre-filled, so do not include one.
# Color codes supported here, guide: https://wiki.ess3.net/mc
RulesMessage:
  - "No Griefing: Griefing is against the rules unless you clean it up to what it was before."
  - "No Hacking: Don't use hacked clients, x-ray, auto clickers, etc. Just don't."
  - "Limit Swearing: Don't overdo it, I don't care about some light swearing but just keep it chill."
  - "No Inappropriate Things: Art, text chat, voice chat, I don't really care, just keep it appropriate."
  - "No Keeping Death Items: If you kill someone, you have to give their items back."
  - "France isn't real: To play on the server you must accept that France isn't real."
  - "Respect the faceless old woman who lives in your house and the creatures in your walls: Also, leave offerings for them."

# France Joke
# This is an inside joke on our server.
# Disabled by default, change the below value to true to enable.
# If enabled, sends a message to a player when they send only the word France/French in chat.
FranceJoke: false