# NoNameCore by BowFun
# A core plugin to add extras to the Not-yet-named Server.

# Prefix - Starts every message sent by the plugin.
# Color codes supported here, guide: https://wiki.ess3.net/mc
Prefix: "&8[&dNo Name Core&8]"

# Welcome Message - Sends to players after they join (3 sec delay)
# Color codes supported here, guide: https://wiki.ess3.net/mc
WelcomeMessage:
  - "&8-- &dNot-yet-named Server &8--"
  - "&bJoin Proximity Chat: /voice"
  - "&9Join the Discord: /discord"